name: autoSignIn

on:
  push:
    branches: [  main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "05 16 * * *" 


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: SignIn
      run: |
        python ./autoSignIn.py
      env:
        SERVER: ${{ secrets.SERVER }}
        SCKEY: ${{ secrets.SCKEY }}
        SCHOOL_NO: ${{secrets.SCHOOL_NO}}
        STUDENT_NO: ${{secrets.STUDENT_NO}}
        MAIL_PW: ${{secrets.MAIL_PW}}
        MAIL_SENDER: ${{secrets.MAIL_SENDER}}
